/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetCompletedPaymentFormOutput struct for GetCompletedPaymentFormOutput
type GetCompletedPaymentFormOutput struct {
	Form *PaymentFormDetails `json:"form,omitempty"`
	Error *Error `json:"error,omitempty"`
}

// NewGetCompletedPaymentFormOutput instantiates a new GetCompletedPaymentFormOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCompletedPaymentFormOutput() *GetCompletedPaymentFormOutput {
	this := GetCompletedPaymentFormOutput{}
	return &this
}

// NewGetCompletedPaymentFormOutputWithDefaults instantiates a new GetCompletedPaymentFormOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCompletedPaymentFormOutputWithDefaults() *GetCompletedPaymentFormOutput {
	this := GetCompletedPaymentFormOutput{}
	return &this
}

// GetForm returns the Form field value if set, zero value otherwise.
func (o *GetCompletedPaymentFormOutput) GetForm() PaymentFormDetails {
	if o == nil || o.Form == nil {
		var ret PaymentFormDetails
		return ret
	}
	return *o.Form
}

// GetFormOk returns a tuple with the Form field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCompletedPaymentFormOutput) GetFormOk() (*PaymentFormDetails, bool) {
	if o == nil || o.Form == nil {
		return nil, false
	}
	return o.Form, true
}

// HasForm returns a boolean if a field has been set.
func (o *GetCompletedPaymentFormOutput) HasForm() bool {
	if o != nil && o.Form != nil {
		return true
	}

	return false
}

// SetForm gets a reference to the given PaymentFormDetails and assigns it to the Form field.
func (o *GetCompletedPaymentFormOutput) SetForm(v PaymentFormDetails) {
	o.Form = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetCompletedPaymentFormOutput) GetError() Error {
	if o == nil || o.Error == nil {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCompletedPaymentFormOutput) GetErrorOk() (*Error, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetCompletedPaymentFormOutput) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *GetCompletedPaymentFormOutput) SetError(v Error) {
	o.Error = &v
}

func (o GetCompletedPaymentFormOutput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Form != nil {
		toSerialize["form"] = o.Form
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableGetCompletedPaymentFormOutput struct {
	value *GetCompletedPaymentFormOutput
	isSet bool
}

func (v NullableGetCompletedPaymentFormOutput) Get() *GetCompletedPaymentFormOutput {
	return v.value
}

func (v *NullableGetCompletedPaymentFormOutput) Set(val *GetCompletedPaymentFormOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCompletedPaymentFormOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCompletedPaymentFormOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCompletedPaymentFormOutput(val *GetCompletedPaymentFormOutput) *NullableGetCompletedPaymentFormOutput {
	return &NullableGetCompletedPaymentFormOutput{value: val, isSet: true}
}

func (v NullableGetCompletedPaymentFormOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCompletedPaymentFormOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


