/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MoneyInTransferInitInput struct for MoneyInTransferInitInput
type MoneyInTransferInitInput struct {
	// returnUrl in case of success
	ReturnUrl string `json:"returnUrl"`
	// cancelUrl in case of cancellation
	CancelUrl string `json:"cancelUrl"`
	// errorUrl in case of error
	ErrorUrl string `json:"errorUrl"`
	// The country code associated with the payment bank. ISO Alpha-2 codes accepted: (FR) France, (ES) Spain, (IT) Italy, (DE) Germany, and (PT) Portugal
	CountryCode string `json:"countryCode"`
	// If you use the bankId in the call, the end-user will be redirected to their bank. They will not have to select a bank from a list provided. To get a comprehensive list of `bankIds` call the `GET v2/moneyins/paybybank/transfer/banks` specifying the ISO Alpha-2 Country Code for example FR for France.
	BankId *string `json:"bankId,omitempty"`
	// Unique ID of the call, generated by your server. This ID can be used as a search field when looking for operation details
	Reference *string `json:"reference,omitempty"`
	// Payment Account ID to Credit
	AccountId string `json:"accountId"`
	// Amount to Debit  Amounts are given as integer numbers in cents
	TotalAmount *int32 `json:"totalAmount,omitempty"`
	// Your Fee  Amounts are given as integer numbers in cents
	CommissionAmount *int32 `json:"commissionAmount,omitempty"`
	// Comment Regarding the Transaction
	Comment *string `json:"comment,omitempty"`
	// If true:  1. [amountCom] will be ignored and will be replaced with Lemonway's fee    2. You will not receive any fee
	AutoCommission *bool `json:"autoCommission,omitempty"`
}

// NewMoneyInTransferInitInput instantiates a new MoneyInTransferInitInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoneyInTransferInitInput(returnUrl string, cancelUrl string, errorUrl string, countryCode string, accountId string) *MoneyInTransferInitInput {
	this := MoneyInTransferInitInput{}
	this.ReturnUrl = returnUrl
	this.CancelUrl = cancelUrl
	this.ErrorUrl = errorUrl
	this.CountryCode = countryCode
	this.AccountId = accountId
	return &this
}

// NewMoneyInTransferInitInputWithDefaults instantiates a new MoneyInTransferInitInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoneyInTransferInitInputWithDefaults() *MoneyInTransferInitInput {
	this := MoneyInTransferInitInput{}
	return &this
}

// GetReturnUrl returns the ReturnUrl field value
func (o *MoneyInTransferInitInput) GetReturnUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetReturnUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnUrl, true
}

// SetReturnUrl sets field value
func (o *MoneyInTransferInitInput) SetReturnUrl(v string) {
	o.ReturnUrl = v
}

// GetCancelUrl returns the CancelUrl field value
func (o *MoneyInTransferInitInput) GetCancelUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CancelUrl
}

// GetCancelUrlOk returns a tuple with the CancelUrl field value
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetCancelUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CancelUrl, true
}

// SetCancelUrl sets field value
func (o *MoneyInTransferInitInput) SetCancelUrl(v string) {
	o.CancelUrl = v
}

// GetErrorUrl returns the ErrorUrl field value
func (o *MoneyInTransferInitInput) GetErrorUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorUrl
}

// GetErrorUrlOk returns a tuple with the ErrorUrl field value
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetErrorUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorUrl, true
}

// SetErrorUrl sets field value
func (o *MoneyInTransferInitInput) SetErrorUrl(v string) {
	o.ErrorUrl = v
}

// GetCountryCode returns the CountryCode field value
func (o *MoneyInTransferInitInput) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *MoneyInTransferInitInput) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetBankId returns the BankId field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetBankId() string {
	if o == nil || o.BankId == nil {
		var ret string
		return ret
	}
	return *o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetBankIdOk() (*string, bool) {
	if o == nil || o.BankId == nil {
		return nil, false
	}
	return o.BankId, true
}

// HasBankId returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasBankId() bool {
	if o != nil && o.BankId != nil {
		return true
	}

	return false
}

// SetBankId gets a reference to the given string and assigns it to the BankId field.
func (o *MoneyInTransferInitInput) SetBankId(v string) {
	o.BankId = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetReference() string {
	if o == nil || o.Reference == nil {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetReferenceOk() (*string, bool) {
	if o == nil || o.Reference == nil {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasReference() bool {
	if o != nil && o.Reference != nil {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *MoneyInTransferInitInput) SetReference(v string) {
	o.Reference = &v
}

// GetAccountId returns the AccountId field value
func (o *MoneyInTransferInitInput) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *MoneyInTransferInitInput) SetAccountId(v string) {
	o.AccountId = v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetTotalAmount() int32 {
	if o == nil || o.TotalAmount == nil {
		var ret int32
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetTotalAmountOk() (*int32, bool) {
	if o == nil || o.TotalAmount == nil {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasTotalAmount() bool {
	if o != nil && o.TotalAmount != nil {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given int32 and assigns it to the TotalAmount field.
func (o *MoneyInTransferInitInput) SetTotalAmount(v int32) {
	o.TotalAmount = &v
}

// GetCommissionAmount returns the CommissionAmount field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetCommissionAmount() int32 {
	if o == nil || o.CommissionAmount == nil {
		var ret int32
		return ret
	}
	return *o.CommissionAmount
}

// GetCommissionAmountOk returns a tuple with the CommissionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetCommissionAmountOk() (*int32, bool) {
	if o == nil || o.CommissionAmount == nil {
		return nil, false
	}
	return o.CommissionAmount, true
}

// HasCommissionAmount returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasCommissionAmount() bool {
	if o != nil && o.CommissionAmount != nil {
		return true
	}

	return false
}

// SetCommissionAmount gets a reference to the given int32 and assigns it to the CommissionAmount field.
func (o *MoneyInTransferInitInput) SetCommissionAmount(v int32) {
	o.CommissionAmount = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *MoneyInTransferInitInput) SetComment(v string) {
	o.Comment = &v
}

// GetAutoCommission returns the AutoCommission field value if set, zero value otherwise.
func (o *MoneyInTransferInitInput) GetAutoCommission() bool {
	if o == nil || o.AutoCommission == nil {
		var ret bool
		return ret
	}
	return *o.AutoCommission
}

// GetAutoCommissionOk returns a tuple with the AutoCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInTransferInitInput) GetAutoCommissionOk() (*bool, bool) {
	if o == nil || o.AutoCommission == nil {
		return nil, false
	}
	return o.AutoCommission, true
}

// HasAutoCommission returns a boolean if a field has been set.
func (o *MoneyInTransferInitInput) HasAutoCommission() bool {
	if o != nil && o.AutoCommission != nil {
		return true
	}

	return false
}

// SetAutoCommission gets a reference to the given bool and assigns it to the AutoCommission field.
func (o *MoneyInTransferInitInput) SetAutoCommission(v bool) {
	o.AutoCommission = &v
}

func (o MoneyInTransferInitInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["returnUrl"] = o.ReturnUrl
	}
	if true {
		toSerialize["cancelUrl"] = o.CancelUrl
	}
	if true {
		toSerialize["errorUrl"] = o.ErrorUrl
	}
	if true {
		toSerialize["countryCode"] = o.CountryCode
	}
	if o.BankId != nil {
		toSerialize["bankId"] = o.BankId
	}
	if o.Reference != nil {
		toSerialize["reference"] = o.Reference
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if o.TotalAmount != nil {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if o.CommissionAmount != nil {
		toSerialize["commissionAmount"] = o.CommissionAmount
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.AutoCommission != nil {
		toSerialize["autoCommission"] = o.AutoCommission
	}
	return json.Marshal(toSerialize)
}

type NullableMoneyInTransferInitInput struct {
	value *MoneyInTransferInitInput
	isSet bool
}

func (v NullableMoneyInTransferInitInput) Get() *MoneyInTransferInitInput {
	return v.value
}

func (v *NullableMoneyInTransferInitInput) Set(val *MoneyInTransferInitInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMoneyInTransferInitInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMoneyInTransferInitInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoneyInTransferInitInput(val *MoneyInTransferInitInput) *NullableMoneyInTransferInitInput {
	return &NullableMoneyInTransferInitInput{value: val, isSet: true}
}

func (v NullableMoneyInTransferInitInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoneyInTransferInitInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


