/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransactionRefund struct for TransactionRefund
type TransactionRefund struct {
	// 0: Success  4: Pending  6: PSP Error
	Status *int32 `json:"status,omitempty"`
	// Debited Account
	SenderAccountId *string `json:"senderAccountId,omitempty"`
	// Debited Amount  Amounts are represented in cents (Euros)
	DebitAmount *int32 `json:"debitAmount,omitempty"`
	// IBAN ID
	IbanId *int64 `json:"IbanId,omitempty"`
	MaskedLabel *string `json:"maskedLabel,omitempty"`
	BankStatus *string `json:"bankStatus,omitempty"`
	PSP *PSP `json:"PSP,omitempty"`
	// Money-In - ID responsible for the chargeback
	OriginId *int64 `json:"originId,omitempty"`
	BuyNowPayLaterInfo *BnplInfo `json:"buyNowPayLaterInfo,omitempty"`
	// Transaction ID
	Id *int64 `json:"id,omitempty"`
	// Payment Method    0 Card      1 Bank transfer (MoneyIn)       3 Bank transfer (MoneyOut)       4 P2P      13 iDEAL      14 SEPA DirectDebit      15 Cheque      17 Sofort      19 Multibanco      21 MBWAY      23 Pagare        30 BNPL    35 PayPal     ---   **Important:** The following services have been discontinued.      16 Neosurf    18 PFS Physical Card    20 Payshop    22 Polish Instant Transfer     24 MobilePay  25 Paytrail  26 WeChat    27 P24    28 MoneyIn by TPE    29 Trustly
	Method *int32 `json:"method,omitempty"`
	// Payment Method Details  0 Standard  1 Pay By Bank<br/>0 = STANDARD.<br/>1 = PAY_BY_BANK.<br/>
	MethodDetails *int32 `json:"methodDetails,omitempty"`
	// Transaction initialization date, UTC Unix timestamp
	Date *int32 `json:"date,omitempty"`
	// Your fee  Amounts are given as integer numbers in cents
	CommissionAmount *int32 `json:"commissionAmount,omitempty"`
	// Comment
	Comment *string `json:"comment,omitempty"`
	// Transaction execution date
	ExecutionDate *int32 `json:"executionDate,omitempty"`
	LemonWayCommission *LemonWayCommission `json:"lemonWayCommission,omitempty"`
	// Unique ID generated by your server
	Reference *string `json:"reference,omitempty"`
}

// NewTransactionRefund instantiates a new TransactionRefund object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionRefund() *TransactionRefund {
	this := TransactionRefund{}
	return &this
}

// NewTransactionRefundWithDefaults instantiates a new TransactionRefund object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionRefundWithDefaults() *TransactionRefund {
	this := TransactionRefund{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TransactionRefund) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TransactionRefund) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *TransactionRefund) SetStatus(v int32) {
	o.Status = &v
}

// GetSenderAccountId returns the SenderAccountId field value if set, zero value otherwise.
func (o *TransactionRefund) GetSenderAccountId() string {
	if o == nil || o.SenderAccountId == nil {
		var ret string
		return ret
	}
	return *o.SenderAccountId
}

// GetSenderAccountIdOk returns a tuple with the SenderAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetSenderAccountIdOk() (*string, bool) {
	if o == nil || o.SenderAccountId == nil {
		return nil, false
	}
	return o.SenderAccountId, true
}

// HasSenderAccountId returns a boolean if a field has been set.
func (o *TransactionRefund) HasSenderAccountId() bool {
	if o != nil && o.SenderAccountId != nil {
		return true
	}

	return false
}

// SetSenderAccountId gets a reference to the given string and assigns it to the SenderAccountId field.
func (o *TransactionRefund) SetSenderAccountId(v string) {
	o.SenderAccountId = &v
}

// GetDebitAmount returns the DebitAmount field value if set, zero value otherwise.
func (o *TransactionRefund) GetDebitAmount() int32 {
	if o == nil || o.DebitAmount == nil {
		var ret int32
		return ret
	}
	return *o.DebitAmount
}

// GetDebitAmountOk returns a tuple with the DebitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetDebitAmountOk() (*int32, bool) {
	if o == nil || o.DebitAmount == nil {
		return nil, false
	}
	return o.DebitAmount, true
}

// HasDebitAmount returns a boolean if a field has been set.
func (o *TransactionRefund) HasDebitAmount() bool {
	if o != nil && o.DebitAmount != nil {
		return true
	}

	return false
}

// SetDebitAmount gets a reference to the given int32 and assigns it to the DebitAmount field.
func (o *TransactionRefund) SetDebitAmount(v int32) {
	o.DebitAmount = &v
}

// GetIbanId returns the IbanId field value if set, zero value otherwise.
func (o *TransactionRefund) GetIbanId() int64 {
	if o == nil || o.IbanId == nil {
		var ret int64
		return ret
	}
	return *o.IbanId
}

// GetIbanIdOk returns a tuple with the IbanId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetIbanIdOk() (*int64, bool) {
	if o == nil || o.IbanId == nil {
		return nil, false
	}
	return o.IbanId, true
}

// HasIbanId returns a boolean if a field has been set.
func (o *TransactionRefund) HasIbanId() bool {
	if o != nil && o.IbanId != nil {
		return true
	}

	return false
}

// SetIbanId gets a reference to the given int64 and assigns it to the IbanId field.
func (o *TransactionRefund) SetIbanId(v int64) {
	o.IbanId = &v
}

// GetMaskedLabel returns the MaskedLabel field value if set, zero value otherwise.
func (o *TransactionRefund) GetMaskedLabel() string {
	if o == nil || o.MaskedLabel == nil {
		var ret string
		return ret
	}
	return *o.MaskedLabel
}

// GetMaskedLabelOk returns a tuple with the MaskedLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetMaskedLabelOk() (*string, bool) {
	if o == nil || o.MaskedLabel == nil {
		return nil, false
	}
	return o.MaskedLabel, true
}

// HasMaskedLabel returns a boolean if a field has been set.
func (o *TransactionRefund) HasMaskedLabel() bool {
	if o != nil && o.MaskedLabel != nil {
		return true
	}

	return false
}

// SetMaskedLabel gets a reference to the given string and assigns it to the MaskedLabel field.
func (o *TransactionRefund) SetMaskedLabel(v string) {
	o.MaskedLabel = &v
}

// GetBankStatus returns the BankStatus field value if set, zero value otherwise.
func (o *TransactionRefund) GetBankStatus() string {
	if o == nil || o.BankStatus == nil {
		var ret string
		return ret
	}
	return *o.BankStatus
}

// GetBankStatusOk returns a tuple with the BankStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetBankStatusOk() (*string, bool) {
	if o == nil || o.BankStatus == nil {
		return nil, false
	}
	return o.BankStatus, true
}

// HasBankStatus returns a boolean if a field has been set.
func (o *TransactionRefund) HasBankStatus() bool {
	if o != nil && o.BankStatus != nil {
		return true
	}

	return false
}

// SetBankStatus gets a reference to the given string and assigns it to the BankStatus field.
func (o *TransactionRefund) SetBankStatus(v string) {
	o.BankStatus = &v
}

// GetPSP returns the PSP field value if set, zero value otherwise.
func (o *TransactionRefund) GetPSP() PSP {
	if o == nil || o.PSP == nil {
		var ret PSP
		return ret
	}
	return *o.PSP
}

// GetPSPOk returns a tuple with the PSP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetPSPOk() (*PSP, bool) {
	if o == nil || o.PSP == nil {
		return nil, false
	}
	return o.PSP, true
}

// HasPSP returns a boolean if a field has been set.
func (o *TransactionRefund) HasPSP() bool {
	if o != nil && o.PSP != nil {
		return true
	}

	return false
}

// SetPSP gets a reference to the given PSP and assigns it to the PSP field.
func (o *TransactionRefund) SetPSP(v PSP) {
	o.PSP = &v
}

// GetOriginId returns the OriginId field value if set, zero value otherwise.
func (o *TransactionRefund) GetOriginId() int64 {
	if o == nil || o.OriginId == nil {
		var ret int64
		return ret
	}
	return *o.OriginId
}

// GetOriginIdOk returns a tuple with the OriginId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetOriginIdOk() (*int64, bool) {
	if o == nil || o.OriginId == nil {
		return nil, false
	}
	return o.OriginId, true
}

// HasOriginId returns a boolean if a field has been set.
func (o *TransactionRefund) HasOriginId() bool {
	if o != nil && o.OriginId != nil {
		return true
	}

	return false
}

// SetOriginId gets a reference to the given int64 and assigns it to the OriginId field.
func (o *TransactionRefund) SetOriginId(v int64) {
	o.OriginId = &v
}

// GetBuyNowPayLaterInfo returns the BuyNowPayLaterInfo field value if set, zero value otherwise.
func (o *TransactionRefund) GetBuyNowPayLaterInfo() BnplInfo {
	if o == nil || o.BuyNowPayLaterInfo == nil {
		var ret BnplInfo
		return ret
	}
	return *o.BuyNowPayLaterInfo
}

// GetBuyNowPayLaterInfoOk returns a tuple with the BuyNowPayLaterInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetBuyNowPayLaterInfoOk() (*BnplInfo, bool) {
	if o == nil || o.BuyNowPayLaterInfo == nil {
		return nil, false
	}
	return o.BuyNowPayLaterInfo, true
}

// HasBuyNowPayLaterInfo returns a boolean if a field has been set.
func (o *TransactionRefund) HasBuyNowPayLaterInfo() bool {
	if o != nil && o.BuyNowPayLaterInfo != nil {
		return true
	}

	return false
}

// SetBuyNowPayLaterInfo gets a reference to the given BnplInfo and assigns it to the BuyNowPayLaterInfo field.
func (o *TransactionRefund) SetBuyNowPayLaterInfo(v BnplInfo) {
	o.BuyNowPayLaterInfo = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TransactionRefund) GetId() int64 {
	if o == nil || o.Id == nil {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetIdOk() (*int64, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TransactionRefund) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *TransactionRefund) SetId(v int64) {
	o.Id = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *TransactionRefund) GetMethod() int32 {
	if o == nil || o.Method == nil {
		var ret int32
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetMethodOk() (*int32, bool) {
	if o == nil || o.Method == nil {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *TransactionRefund) HasMethod() bool {
	if o != nil && o.Method != nil {
		return true
	}

	return false
}

// SetMethod gets a reference to the given int32 and assigns it to the Method field.
func (o *TransactionRefund) SetMethod(v int32) {
	o.Method = &v
}

// GetMethodDetails returns the MethodDetails field value if set, zero value otherwise.
func (o *TransactionRefund) GetMethodDetails() int32 {
	if o == nil || o.MethodDetails == nil {
		var ret int32
		return ret
	}
	return *o.MethodDetails
}

// GetMethodDetailsOk returns a tuple with the MethodDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetMethodDetailsOk() (*int32, bool) {
	if o == nil || o.MethodDetails == nil {
		return nil, false
	}
	return o.MethodDetails, true
}

// HasMethodDetails returns a boolean if a field has been set.
func (o *TransactionRefund) HasMethodDetails() bool {
	if o != nil && o.MethodDetails != nil {
		return true
	}

	return false
}

// SetMethodDetails gets a reference to the given int32 and assigns it to the MethodDetails field.
func (o *TransactionRefund) SetMethodDetails(v int32) {
	o.MethodDetails = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *TransactionRefund) GetDate() int32 {
	if o == nil || o.Date == nil {
		var ret int32
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetDateOk() (*int32, bool) {
	if o == nil || o.Date == nil {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *TransactionRefund) HasDate() bool {
	if o != nil && o.Date != nil {
		return true
	}

	return false
}

// SetDate gets a reference to the given int32 and assigns it to the Date field.
func (o *TransactionRefund) SetDate(v int32) {
	o.Date = &v
}

// GetCommissionAmount returns the CommissionAmount field value if set, zero value otherwise.
func (o *TransactionRefund) GetCommissionAmount() int32 {
	if o == nil || o.CommissionAmount == nil {
		var ret int32
		return ret
	}
	return *o.CommissionAmount
}

// GetCommissionAmountOk returns a tuple with the CommissionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetCommissionAmountOk() (*int32, bool) {
	if o == nil || o.CommissionAmount == nil {
		return nil, false
	}
	return o.CommissionAmount, true
}

// HasCommissionAmount returns a boolean if a field has been set.
func (o *TransactionRefund) HasCommissionAmount() bool {
	if o != nil && o.CommissionAmount != nil {
		return true
	}

	return false
}

// SetCommissionAmount gets a reference to the given int32 and assigns it to the CommissionAmount field.
func (o *TransactionRefund) SetCommissionAmount(v int32) {
	o.CommissionAmount = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *TransactionRefund) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *TransactionRefund) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *TransactionRefund) SetComment(v string) {
	o.Comment = &v
}

// GetExecutionDate returns the ExecutionDate field value if set, zero value otherwise.
func (o *TransactionRefund) GetExecutionDate() int32 {
	if o == nil || o.ExecutionDate == nil {
		var ret int32
		return ret
	}
	return *o.ExecutionDate
}

// GetExecutionDateOk returns a tuple with the ExecutionDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetExecutionDateOk() (*int32, bool) {
	if o == nil || o.ExecutionDate == nil {
		return nil, false
	}
	return o.ExecutionDate, true
}

// HasExecutionDate returns a boolean if a field has been set.
func (o *TransactionRefund) HasExecutionDate() bool {
	if o != nil && o.ExecutionDate != nil {
		return true
	}

	return false
}

// SetExecutionDate gets a reference to the given int32 and assigns it to the ExecutionDate field.
func (o *TransactionRefund) SetExecutionDate(v int32) {
	o.ExecutionDate = &v
}

// GetLemonWayCommission returns the LemonWayCommission field value if set, zero value otherwise.
func (o *TransactionRefund) GetLemonWayCommission() LemonWayCommission {
	if o == nil || o.LemonWayCommission == nil {
		var ret LemonWayCommission
		return ret
	}
	return *o.LemonWayCommission
}

// GetLemonWayCommissionOk returns a tuple with the LemonWayCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetLemonWayCommissionOk() (*LemonWayCommission, bool) {
	if o == nil || o.LemonWayCommission == nil {
		return nil, false
	}
	return o.LemonWayCommission, true
}

// HasLemonWayCommission returns a boolean if a field has been set.
func (o *TransactionRefund) HasLemonWayCommission() bool {
	if o != nil && o.LemonWayCommission != nil {
		return true
	}

	return false
}

// SetLemonWayCommission gets a reference to the given LemonWayCommission and assigns it to the LemonWayCommission field.
func (o *TransactionRefund) SetLemonWayCommission(v LemonWayCommission) {
	o.LemonWayCommission = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *TransactionRefund) GetReference() string {
	if o == nil || o.Reference == nil {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionRefund) GetReferenceOk() (*string, bool) {
	if o == nil || o.Reference == nil {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *TransactionRefund) HasReference() bool {
	if o != nil && o.Reference != nil {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *TransactionRefund) SetReference(v string) {
	o.Reference = &v
}

func (o TransactionRefund) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.SenderAccountId != nil {
		toSerialize["senderAccountId"] = o.SenderAccountId
	}
	if o.DebitAmount != nil {
		toSerialize["debitAmount"] = o.DebitAmount
	}
	if o.IbanId != nil {
		toSerialize["IbanId"] = o.IbanId
	}
	if o.MaskedLabel != nil {
		toSerialize["maskedLabel"] = o.MaskedLabel
	}
	if o.BankStatus != nil {
		toSerialize["bankStatus"] = o.BankStatus
	}
	if o.PSP != nil {
		toSerialize["PSP"] = o.PSP
	}
	if o.OriginId != nil {
		toSerialize["originId"] = o.OriginId
	}
	if o.BuyNowPayLaterInfo != nil {
		toSerialize["buyNowPayLaterInfo"] = o.BuyNowPayLaterInfo
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if o.MethodDetails != nil {
		toSerialize["methodDetails"] = o.MethodDetails
	}
	if o.Date != nil {
		toSerialize["date"] = o.Date
	}
	if o.CommissionAmount != nil {
		toSerialize["commissionAmount"] = o.CommissionAmount
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.ExecutionDate != nil {
		toSerialize["executionDate"] = o.ExecutionDate
	}
	if o.LemonWayCommission != nil {
		toSerialize["lemonWayCommission"] = o.LemonWayCommission
	}
	if o.Reference != nil {
		toSerialize["reference"] = o.Reference
	}
	return json.Marshal(toSerialize)
}

type NullableTransactionRefund struct {
	value *TransactionRefund
	isSet bool
}

func (v NullableTransactionRefund) Get() *TransactionRefund {
	return v.value
}

func (v *NullableTransactionRefund) Set(val *TransactionRefund) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionRefund) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionRefund) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionRefund(val *TransactionRefund) *NullableTransactionRefund {
	return &NullableTransactionRefund{value: val, isSet: true}
}

func (v NullableTransactionRefund) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionRefund) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


