/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AccountBalancesInput struct for AccountBalancesInput
type AccountBalancesInput struct {
	// Date in UTC Seconds  Leave empty to use payment account IDs.
	UpdateDate *string `json:"updateDate,omitempty"`
	// First payment account internal ID, starting from 12.
	InternalAccountIdStart *int64 `json:"internalAccountIdStart,omitempty"`
	// Last payment account internal ID, starting from 12.
	InternalAccountIdEnd *int64 `json:"internalAccountIdEnd,omitempty"`
}

// NewAccountBalancesInput instantiates a new AccountBalancesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountBalancesInput() *AccountBalancesInput {
	this := AccountBalancesInput{}
	return &this
}

// NewAccountBalancesInputWithDefaults instantiates a new AccountBalancesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountBalancesInputWithDefaults() *AccountBalancesInput {
	this := AccountBalancesInput{}
	return &this
}

// GetUpdateDate returns the UpdateDate field value if set, zero value otherwise.
func (o *AccountBalancesInput) GetUpdateDate() string {
	if o == nil || o.UpdateDate == nil {
		var ret string
		return ret
	}
	return *o.UpdateDate
}

// GetUpdateDateOk returns a tuple with the UpdateDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountBalancesInput) GetUpdateDateOk() (*string, bool) {
	if o == nil || o.UpdateDate == nil {
		return nil, false
	}
	return o.UpdateDate, true
}

// HasUpdateDate returns a boolean if a field has been set.
func (o *AccountBalancesInput) HasUpdateDate() bool {
	if o != nil && o.UpdateDate != nil {
		return true
	}

	return false
}

// SetUpdateDate gets a reference to the given string and assigns it to the UpdateDate field.
func (o *AccountBalancesInput) SetUpdateDate(v string) {
	o.UpdateDate = &v
}

// GetInternalAccountIdStart returns the InternalAccountIdStart field value if set, zero value otherwise.
func (o *AccountBalancesInput) GetInternalAccountIdStart() int64 {
	if o == nil || o.InternalAccountIdStart == nil {
		var ret int64
		return ret
	}
	return *o.InternalAccountIdStart
}

// GetInternalAccountIdStartOk returns a tuple with the InternalAccountIdStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountBalancesInput) GetInternalAccountIdStartOk() (*int64, bool) {
	if o == nil || o.InternalAccountIdStart == nil {
		return nil, false
	}
	return o.InternalAccountIdStart, true
}

// HasInternalAccountIdStart returns a boolean if a field has been set.
func (o *AccountBalancesInput) HasInternalAccountIdStart() bool {
	if o != nil && o.InternalAccountIdStart != nil {
		return true
	}

	return false
}

// SetInternalAccountIdStart gets a reference to the given int64 and assigns it to the InternalAccountIdStart field.
func (o *AccountBalancesInput) SetInternalAccountIdStart(v int64) {
	o.InternalAccountIdStart = &v
}

// GetInternalAccountIdEnd returns the InternalAccountIdEnd field value if set, zero value otherwise.
func (o *AccountBalancesInput) GetInternalAccountIdEnd() int64 {
	if o == nil || o.InternalAccountIdEnd == nil {
		var ret int64
		return ret
	}
	return *o.InternalAccountIdEnd
}

// GetInternalAccountIdEndOk returns a tuple with the InternalAccountIdEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountBalancesInput) GetInternalAccountIdEndOk() (*int64, bool) {
	if o == nil || o.InternalAccountIdEnd == nil {
		return nil, false
	}
	return o.InternalAccountIdEnd, true
}

// HasInternalAccountIdEnd returns a boolean if a field has been set.
func (o *AccountBalancesInput) HasInternalAccountIdEnd() bool {
	if o != nil && o.InternalAccountIdEnd != nil {
		return true
	}

	return false
}

// SetInternalAccountIdEnd gets a reference to the given int64 and assigns it to the InternalAccountIdEnd field.
func (o *AccountBalancesInput) SetInternalAccountIdEnd(v int64) {
	o.InternalAccountIdEnd = &v
}

func (o AccountBalancesInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UpdateDate != nil {
		toSerialize["updateDate"] = o.UpdateDate
	}
	if o.InternalAccountIdStart != nil {
		toSerialize["internalAccountIdStart"] = o.InternalAccountIdStart
	}
	if o.InternalAccountIdEnd != nil {
		toSerialize["internalAccountIdEnd"] = o.InternalAccountIdEnd
	}
	return json.Marshal(toSerialize)
}

type NullableAccountBalancesInput struct {
	value *AccountBalancesInput
	isSet bool
}

func (v NullableAccountBalancesInput) Get() *AccountBalancesInput {
	return v.value
}

func (v *NullableAccountBalancesInput) Set(val *AccountBalancesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountBalancesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountBalancesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountBalancesInput(val *AccountBalancesInput) *NullableAccountBalancesInput {
	return &NullableAccountBalancesInput{value: val, isSet: true}
}

func (v NullableAccountBalancesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountBalancesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


