/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MoneyInInput struct for MoneyInInput
type MoneyInInput struct {
	Card CardInfo `json:"card"`
	// **Mercanet Only**  Indicates if the request is delayed and will require validation.  1. If true, payment will only be pre-authorized, you will have to call `MoneyInValidate` within 6 days or [delayedDays] in order to request the card debit.  2. If empty, the default behavior is no delay and no validation necessary (unless stated otherwise in your contract).  3. If false, the card will be debited without delay and without validation necessary.
	IsPreAuth *bool `json:"isPreAuth,omitempty"`
	// **Mercanet Only**  If isPreAuth is not true, this will be ignored.   Please use with caution, if delayedDays &gt; 6, it is possible that the payment will be denied when you try to validate it, because a new authorization will be made.
	DelayedDays *int32 `json:"delayedDays,omitempty"`
	// Leave Empty
	SpecialConfig *string `json:"specialConfig,omitempty"`
	// Unique ID of the call, generated by your server. This ID can be used as a search field when looking for operation details
	Reference *string `json:"reference,omitempty"`
	// Payment Account ID to Credit
	AccountId string `json:"accountId"`
	// Amount to Debit  Amounts are given as integer numbers in cents
	TotalAmount *int32 `json:"totalAmount,omitempty"`
	// Your Fee  Amounts are given as integer numbers in cents
	CommissionAmount *int32 `json:"commissionAmount,omitempty"`
	// Comment Regarding the Transaction
	Comment *string `json:"comment,omitempty"`
	// If true:  1. [amountCom] will be ignored and will be replaced with Lemonway's fee  2. You will not receive any fee
	AutoCommission *bool `json:"autoCommission,omitempty"`
}

// NewMoneyInInput instantiates a new MoneyInInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoneyInInput(card CardInfo, accountId string) *MoneyInInput {
	this := MoneyInInput{}
	this.Card = card
	this.AccountId = accountId
	return &this
}

// NewMoneyInInputWithDefaults instantiates a new MoneyInInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoneyInInputWithDefaults() *MoneyInInput {
	this := MoneyInInput{}
	return &this
}

// GetCard returns the Card field value
func (o *MoneyInInput) GetCard() CardInfo {
	if o == nil {
		var ret CardInfo
		return ret
	}

	return o.Card
}

// GetCardOk returns a tuple with the Card field value
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetCardOk() (*CardInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Card, true
}

// SetCard sets field value
func (o *MoneyInInput) SetCard(v CardInfo) {
	o.Card = v
}

// GetIsPreAuth returns the IsPreAuth field value if set, zero value otherwise.
func (o *MoneyInInput) GetIsPreAuth() bool {
	if o == nil || o.IsPreAuth == nil {
		var ret bool
		return ret
	}
	return *o.IsPreAuth
}

// GetIsPreAuthOk returns a tuple with the IsPreAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetIsPreAuthOk() (*bool, bool) {
	if o == nil || o.IsPreAuth == nil {
		return nil, false
	}
	return o.IsPreAuth, true
}

// HasIsPreAuth returns a boolean if a field has been set.
func (o *MoneyInInput) HasIsPreAuth() bool {
	if o != nil && o.IsPreAuth != nil {
		return true
	}

	return false
}

// SetIsPreAuth gets a reference to the given bool and assigns it to the IsPreAuth field.
func (o *MoneyInInput) SetIsPreAuth(v bool) {
	o.IsPreAuth = &v
}

// GetDelayedDays returns the DelayedDays field value if set, zero value otherwise.
func (o *MoneyInInput) GetDelayedDays() int32 {
	if o == nil || o.DelayedDays == nil {
		var ret int32
		return ret
	}
	return *o.DelayedDays
}

// GetDelayedDaysOk returns a tuple with the DelayedDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetDelayedDaysOk() (*int32, bool) {
	if o == nil || o.DelayedDays == nil {
		return nil, false
	}
	return o.DelayedDays, true
}

// HasDelayedDays returns a boolean if a field has been set.
func (o *MoneyInInput) HasDelayedDays() bool {
	if o != nil && o.DelayedDays != nil {
		return true
	}

	return false
}

// SetDelayedDays gets a reference to the given int32 and assigns it to the DelayedDays field.
func (o *MoneyInInput) SetDelayedDays(v int32) {
	o.DelayedDays = &v
}

// GetSpecialConfig returns the SpecialConfig field value if set, zero value otherwise.
func (o *MoneyInInput) GetSpecialConfig() string {
	if o == nil || o.SpecialConfig == nil {
		var ret string
		return ret
	}
	return *o.SpecialConfig
}

// GetSpecialConfigOk returns a tuple with the SpecialConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetSpecialConfigOk() (*string, bool) {
	if o == nil || o.SpecialConfig == nil {
		return nil, false
	}
	return o.SpecialConfig, true
}

// HasSpecialConfig returns a boolean if a field has been set.
func (o *MoneyInInput) HasSpecialConfig() bool {
	if o != nil && o.SpecialConfig != nil {
		return true
	}

	return false
}

// SetSpecialConfig gets a reference to the given string and assigns it to the SpecialConfig field.
func (o *MoneyInInput) SetSpecialConfig(v string) {
	o.SpecialConfig = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *MoneyInInput) GetReference() string {
	if o == nil || o.Reference == nil {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetReferenceOk() (*string, bool) {
	if o == nil || o.Reference == nil {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *MoneyInInput) HasReference() bool {
	if o != nil && o.Reference != nil {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *MoneyInInput) SetReference(v string) {
	o.Reference = &v
}

// GetAccountId returns the AccountId field value
func (o *MoneyInInput) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *MoneyInInput) SetAccountId(v string) {
	o.AccountId = v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *MoneyInInput) GetTotalAmount() int32 {
	if o == nil || o.TotalAmount == nil {
		var ret int32
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetTotalAmountOk() (*int32, bool) {
	if o == nil || o.TotalAmount == nil {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *MoneyInInput) HasTotalAmount() bool {
	if o != nil && o.TotalAmount != nil {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given int32 and assigns it to the TotalAmount field.
func (o *MoneyInInput) SetTotalAmount(v int32) {
	o.TotalAmount = &v
}

// GetCommissionAmount returns the CommissionAmount field value if set, zero value otherwise.
func (o *MoneyInInput) GetCommissionAmount() int32 {
	if o == nil || o.CommissionAmount == nil {
		var ret int32
		return ret
	}
	return *o.CommissionAmount
}

// GetCommissionAmountOk returns a tuple with the CommissionAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetCommissionAmountOk() (*int32, bool) {
	if o == nil || o.CommissionAmount == nil {
		return nil, false
	}
	return o.CommissionAmount, true
}

// HasCommissionAmount returns a boolean if a field has been set.
func (o *MoneyInInput) HasCommissionAmount() bool {
	if o != nil && o.CommissionAmount != nil {
		return true
	}

	return false
}

// SetCommissionAmount gets a reference to the given int32 and assigns it to the CommissionAmount field.
func (o *MoneyInInput) SetCommissionAmount(v int32) {
	o.CommissionAmount = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *MoneyInInput) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *MoneyInInput) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *MoneyInInput) SetComment(v string) {
	o.Comment = &v
}

// GetAutoCommission returns the AutoCommission field value if set, zero value otherwise.
func (o *MoneyInInput) GetAutoCommission() bool {
	if o == nil || o.AutoCommission == nil {
		var ret bool
		return ret
	}
	return *o.AutoCommission
}

// GetAutoCommissionOk returns a tuple with the AutoCommission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoneyInInput) GetAutoCommissionOk() (*bool, bool) {
	if o == nil || o.AutoCommission == nil {
		return nil, false
	}
	return o.AutoCommission, true
}

// HasAutoCommission returns a boolean if a field has been set.
func (o *MoneyInInput) HasAutoCommission() bool {
	if o != nil && o.AutoCommission != nil {
		return true
	}

	return false
}

// SetAutoCommission gets a reference to the given bool and assigns it to the AutoCommission field.
func (o *MoneyInInput) SetAutoCommission(v bool) {
	o.AutoCommission = &v
}

func (o MoneyInInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["card"] = o.Card
	}
	if o.IsPreAuth != nil {
		toSerialize["isPreAuth"] = o.IsPreAuth
	}
	if o.DelayedDays != nil {
		toSerialize["delayedDays"] = o.DelayedDays
	}
	if o.SpecialConfig != nil {
		toSerialize["specialConfig"] = o.SpecialConfig
	}
	if o.Reference != nil {
		toSerialize["reference"] = o.Reference
	}
	if true {
		toSerialize["accountId"] = o.AccountId
	}
	if o.TotalAmount != nil {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	if o.CommissionAmount != nil {
		toSerialize["commissionAmount"] = o.CommissionAmount
	}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.AutoCommission != nil {
		toSerialize["autoCommission"] = o.AutoCommission
	}
	return json.Marshal(toSerialize)
}

type NullableMoneyInInput struct {
	value *MoneyInInput
	isSet bool
}

func (v NullableMoneyInInput) Get() *MoneyInInput {
	return v.value
}

func (v *NullableMoneyInInput) Set(val *MoneyInInput) {
	v.value = val
	v.isSet = true
}

func (v NullableMoneyInInput) IsSet() bool {
	return v.isSet
}

func (v *NullableMoneyInInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoneyInInput(val *MoneyInInput) *NullableMoneyInInput {
	return &NullableMoneyInInput{value: val, isSet: true}
}

func (v NullableMoneyInInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoneyInInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


