/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PSP struct for PSP
type PSP struct {
	// Get the Error Message from PSP
	Message *string `json:"message,omitempty"`
}

// NewPSP instantiates a new PSP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPSP() *PSP {
	this := PSP{}
	return &this
}

// NewPSPWithDefaults instantiates a new PSP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPSPWithDefaults() *PSP {
	this := PSP{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PSP) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PSP) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PSP) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PSP) SetMessage(v string) {
	o.Message = &v
}

func (o PSP) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullablePSP struct {
	value *PSP
	isSet bool
}

func (v NullablePSP) Get() *PSP {
	return v.value
}

func (v *NullablePSP) Set(val *PSP) {
	v.value = val
	v.isSet = true
}

func (v NullablePSP) IsSet() bool {
	return v.isSet
}

func (v *NullablePSP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePSP(val *PSP) *NullablePSP {
	return &NullablePSP{value: val, isSet: true}
}

func (v NullablePSP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePSP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


