/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UnregisterSddMandateInput struct for UnregisterSddMandateInput
type UnregisterSddMandateInput struct {
	// Payment Account ID
	Account string `json:"account"`
}

// NewUnregisterSddMandateInput instantiates a new UnregisterSddMandateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnregisterSddMandateInput(account string) *UnregisterSddMandateInput {
	this := UnregisterSddMandateInput{}
	this.Account = account
	return &this
}

// NewUnregisterSddMandateInputWithDefaults instantiates a new UnregisterSddMandateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnregisterSddMandateInputWithDefaults() *UnregisterSddMandateInput {
	this := UnregisterSddMandateInput{}
	return &this
}

// GetAccount returns the Account field value
func (o *UnregisterSddMandateInput) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *UnregisterSddMandateInput) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *UnregisterSddMandateInput) SetAccount(v string) {
	o.Account = v
}

func (o UnregisterSddMandateInput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableUnregisterSddMandateInput struct {
	value *UnregisterSddMandateInput
	isSet bool
}

func (v NullableUnregisterSddMandateInput) Get() *UnregisterSddMandateInput {
	return v.value
}

func (v *NullableUnregisterSddMandateInput) Set(val *UnregisterSddMandateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUnregisterSddMandateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUnregisterSddMandateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnregisterSddMandateInput(val *UnregisterSddMandateInput) *NullableUnregisterSddMandateInput {
	return &NullableUnregisterSddMandateInput{value: val, isSet: true}
}

func (v NullableUnregisterSddMandateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnregisterSddMandateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


