/*
Lemonway DirectKit API 2.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetPaymentDetailsOutput struct for GetPaymentDetailsOutput
type GetPaymentDetailsOutput struct {
	Transactions *TransactionsTransactionP2P `json:"transactions,omitempty"`
	Links *Links `json:"_links,omitempty"`
	Error *Error `json:"error,omitempty"`
}

// NewGetPaymentDetailsOutput instantiates a new GetPaymentDetailsOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPaymentDetailsOutput() *GetPaymentDetailsOutput {
	this := GetPaymentDetailsOutput{}
	return &this
}

// NewGetPaymentDetailsOutputWithDefaults instantiates a new GetPaymentDetailsOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPaymentDetailsOutputWithDefaults() *GetPaymentDetailsOutput {
	this := GetPaymentDetailsOutput{}
	return &this
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *GetPaymentDetailsOutput) GetTransactions() TransactionsTransactionP2P {
	if o == nil || o.Transactions == nil {
		var ret TransactionsTransactionP2P
		return ret
	}
	return *o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPaymentDetailsOutput) GetTransactionsOk() (*TransactionsTransactionP2P, bool) {
	if o == nil || o.Transactions == nil {
		return nil, false
	}
	return o.Transactions, true
}

// HasTransactions returns a boolean if a field has been set.
func (o *GetPaymentDetailsOutput) HasTransactions() bool {
	if o != nil && o.Transactions != nil {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given TransactionsTransactionP2P and assigns it to the Transactions field.
func (o *GetPaymentDetailsOutput) SetTransactions(v TransactionsTransactionP2P) {
	o.Transactions = &v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetPaymentDetailsOutput) GetLinks() Links {
	if o == nil || o.Links == nil {
		var ret Links
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPaymentDetailsOutput) GetLinksOk() (*Links, bool) {
	if o == nil || o.Links == nil {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetPaymentDetailsOutput) HasLinks() bool {
	if o != nil && o.Links != nil {
		return true
	}

	return false
}

// SetLinks gets a reference to the given Links and assigns it to the Links field.
func (o *GetPaymentDetailsOutput) SetLinks(v Links) {
	o.Links = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetPaymentDetailsOutput) GetError() Error {
	if o == nil || o.Error == nil {
		var ret Error
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPaymentDetailsOutput) GetErrorOk() (*Error, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetPaymentDetailsOutput) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given Error and assigns it to the Error field.
func (o *GetPaymentDetailsOutput) SetError(v Error) {
	o.Error = &v
}

func (o GetPaymentDetailsOutput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Transactions != nil {
		toSerialize["transactions"] = o.Transactions
	}
	if o.Links != nil {
		toSerialize["_links"] = o.Links
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableGetPaymentDetailsOutput struct {
	value *GetPaymentDetailsOutput
	isSet bool
}

func (v NullableGetPaymentDetailsOutput) Get() *GetPaymentDetailsOutput {
	return v.value
}

func (v *NullableGetPaymentDetailsOutput) Set(val *GetPaymentDetailsOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPaymentDetailsOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPaymentDetailsOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPaymentDetailsOutput(val *GetPaymentDetailsOutput) *NullableGetPaymentDetailsOutput {
	return &NullableGetPaymentDetailsOutput{value: val, isSet: true}
}

func (v NullableGetPaymentDetailsOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPaymentDetailsOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


